spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc8th
    username: root
    password: Deft201902619@
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        database: mysql
        database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        default_batch_fetch_size: 1000

    open-in-view: false
jwt:
  token:
    secretKey: umceightfightingjwttokenauthentication
    expiration:
      access: 14400000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

error:
  alert:
    enabled: false

webhook:
  discord:
    url: https://discord.com/api/webhooks/1370995959156445294/_vFpNazHORz09A__u1iGyNn7-oktc_lvUJcs1xLhmw6eJ38UdT8475L0HfET1SEpoBAn
